### PR TITLE
feat: added 'baths' svg to assets

### PR DESCRIPTION
**Pull request by willemodendaal**
Added a new 'baths' icon to /assets.

It looks like this:

image

There were no styled-icons that match this exactly.

### CODE REVIEW

**Review by seagyn — APPROVED** [review]
Is this on "strategy"?

**Comment by fjlaubscher** [comment]
I think this should go into master first?

**Review by fjlaubscher — APPROVED** [review]

**Comment by willemodendaal** [comment]
> Is this on "strategy"?

I'm not sure... I'll take a stab at writing down the strategy to confirm if everyone's on the same page.

**Comment by fjlaubscher** [comment]
> > Is this on "strategy"?
> 
> I'm not sure... I'll take a stab at writing down the strategy to confirm if everyone's on the same page.

Y'all should have a meeting about this first and draw up a roadmap on miro.

**Comment by seagyn** [comment]
> > > Is this on "strategy"?
> > 
> > 
> > I'm not sure... I'll take a stab at writing down the strategy to confirm if everyone's on the same page.
> 
> Y'all should have a meeting about this first and draw up a roadmap on miro.

Does that mean we have to get Eben involved?

**Comment by fjlaubscher** [comment]
> > > > Is this on "strategy"?
> > > 
> > > 
> > > I'm not sure... I'll take a stab at writing down the strategy to confirm if everyone's on the same page.
> > 
> > 
> > Y'all should have a meeting about this first and draw up a roadmap on miro.
> 
> Does that mean we have to get Eben involved?

Ahahaha I just realized this is an open source repo and anyone can see this conversation 😆

**Pull request merged**
